### ISSUE TITLE
Feature Request: Capture Errors

### ISSUE THREAD

**Issue by sh00t2kill** [njanik/hayward-pool-heater-mqtt#12]
Is it possible to capture the error states of the pump ?

Eg this morning i turned my heat pump on, and the returned state was on `pool/power` was 1, however it didnt turn on due to an E03 code, which means no water flow.

Turns out my chlorinator had thrown a low water level error (i think because the pump had an air pocket and didnt start up quick enough), which was overrding the junction box command for water from the heat pump.

**Comment by njanik** [comment]
Sorry, I can't do that because to be able to get this error code, I have to reproduce it.
Also, my data capture setup was connected to the heat pump several years ago. This has not been the case for a long time. If you can capture the data yourself, I can help you to find the error code in the trame.
